apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"wordpress:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"wordpress\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2022-01-31T18:42:02Z"
    generation: 2
    labels:
      app: wordpress
      app.kubernetes.io/component: wordpress
      app.kubernetes.io/instance: wordpress
    name: wordpress
    namespace: wordpress
    resourceVersion: "11059375"
    uid: 030199ce-9ba9-4b5c-aad7-e9f4273ff216
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: wordpress
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: wordpress
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/wp/wordpress@sha256:11963d0426d6b512abfda3be68913754421aa7c691451c5020f0a52835ba6bae
          imagePullPolicy: IfNotPresent
          name: wordpress
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""