apiVersion: v1
data:
  database-name: c2FtcGxlZGI=
  database-password: ZXR1eHdVd3VjRmhOVzNLTg==
  database-root-password: dlNlbVJmM1QybFYwZHVhWQ==
  database-user: dXNlckNKWA==
kind: Secret
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  creationTimestamp: "2022-01-31T18:39:27Z"
  labels:
    app: mariadb-ephemeral
    app.kubernetes.io/component: mariadb-ephemeral
    app.kubernetes.io/instance: mariadb-ephemeral
    template: mariadb-ephemeral-template
  name: mariadb
  namespace: wordpress
  resourceVersion: "11057854"
  uid: bc14866d-cf6d-49a8-8987-1a38e0e10d6e
type: Opaque
